### ISSUE TITLE
Import via file upload - works?

### ISSUE THREAD

**Issue by alexdrupal** [w-vision/ImportDefinitions#33]
It doesn't works for me so far. This is the error i'm receiving:

```
<br />
<b>Fatal error</b>:  Uncaught Zend_Json_Exception: Decoding failed: Syntax error in /var/www/pimcore-live/vendor/zendframework/zendframework1/library/Zend/Json.php:97
Stack trace:
#0 /var/www/pimcore-live/plugins/ImportDefinitions/controllers/Admin/DefinitionController.php(191): Zend_Json::decode('&quot;model&quot;,&quot;price&quot;...')
#1 /var/www/pimcore-live/vendor/zendframework/zendframework1/library/Zend/Controller/Action.php(516): ImportDefinitions_Admin_DefinitionController-&gt;importAction()
#2 /var/www/pimcore-live/vendor/zendframework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action-&gt;dispatch('importAction')
#3 /var/www/pimcore-live/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard-&gt;dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#4 /var/www/pimcore-live/pimcore/lib/Pimcore.php(159): Zend_Controller_Front-&gt;dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#5 /var/ww in <b>/var/www/pimcore-live/vendor/zendframework/zendframework1/library/Zend/Json.php</b> on line <b>97</b><br />
```

**Comment by dpfaffenbauer** [comment]
ha? What do you mean?

**Comment by alexdrupal** [comment]
I mean I try to use Import button on Import definition screen. I try to upload csv file.
Please, see the attached image.
![pimcore live com pimcore](https://user-images.githubusercontent.com/38625/28608540-60bcacc4-71e9-11e7-9d3c-63542c882587.png)

**Comment by dpfaffenbauer** [comment]
No, that button is supposed to mean: "Import existing Import Definitions JSON File". So it works like this:
 - Create a definition
 - Click the Export Button, you'll get a json file
 - Click the Import Button and import the json file.

**Comment by alexdrupal** [comment]
Oh... ok. Maybe rename it to Import/Export Definition?

**Comment by dpfaffenbauer** [comment]
Not sure about that, Pimcore does it similar. If you have experience with Pimcore this should be clear. But I will add some docs for that.

**Comment by dpfaffenbauer** [comment]
changed translation in Version 2 for Pimcore 5.
